name: Lint PHP files
on: [push, pull_request]

jobs:
  php-73:
    runs-on: ubuntu-latest
    steps:
      - uses: prestashop/github-action-php-lint/7.3@v2.1

  php-74:
    runs-on: ubuntu-latest
    steps:
      - uses: prestashop/github-action-php-lint/7.4@v2.1

  php-81:
    runs-on: ubuntu-latest
    steps:
      - uses: prestashop/github-action-php-lint/8.1@v2.1

  php-82:
    runs-on: ubuntu-latest
    steps:
      - uses: prestashop/github-action-php-lint/8.2@v2.1
