name: Lint PHP files
on: [push, pull_request]

jobs:
  php-70:
    runs-on: ubuntu-latest
    steps:
      - uses: StephaneBour/actions-php-lint@7.0
        with:
          dir: './'

  php-71:
    runs-on: ubuntu-latest
    steps:
      - uses: StephaneBour/actions-php-lint@7.1
        with:
          dir: './'

  php-72:
    runs-on: ubuntu-latest
    steps:
      - uses: StephaneBour/actions-php-lint@7.2
        with:
          dir: './'

  php-73:
    runs-on: ubuntu-latest
    steps:
      - uses: StephaneBour/actions-php-lint@7.3
        with:
          dir: './'

  php-74:
    runs-on: ubuntu-latest
    steps:
      - uses: StephaneBour/actions-php-lint@7.4
        with:
          dir: './'
