name: phpstan

on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                PHP_VERSION: [php71-fpm, php72-fpm]
                MAGENTO_VERSION: [2.2.11, 2.3.5-p1]
                exclude:
                    - PHP_VERSION: php72-fpm
                      MAGENTO_VERSION: 2.2.11
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Start Docker
              run: docker run --detach --name magento-project-community-edition michielgerritsen/magento-project-community-edition:${{ matrix.PHP_VERSION }}-magento${{ matrix.MAGENTO_VERSION }}

            - name: Upload our code into the docker container
              run: docker cp $(pwd) magento-project-community-edition:/data/extensions/

            - name: Install the extensions in Magento
              run: docker exec magento-project-community-edition composer require mollie/magento2:@dev fooman/phpstan-magento2-magic-methods

            - name: Run PHPStan
              run: docker exec magento-project-community-edition /bin/bash -c "./vendor/bin/phpstan analyse -c /data/extensions/*/phpstan.neon /data/extensions"
